spring:
  application:
    name: Premier

  datasource:
    url: jdbc:sqlite:test1.1.db
    driver-class-name: org.sqlite.JDBC

  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update

  mail:
    host: smtp.gmail.com
    port: 587
    username: thanhvu7623@gmail.com
    password: brev bago trwi eeko
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

URL_frontend: http://localhost:63343

#logging:
#  level:
#    root: DEBUG  # Set the log level for the root logger
#    org.springframework: DEBUG  # Set the log level for Spring Framework
#    org.hibernate: DEBUG  # Set the log level for Hibernate

jwt:
  signerKey: KpDU0T82a7oaCgJ5Z98BlR2kIzDiliRHGgXL/xCo2LSjxeJ0tvkaDtWazIPxeP7m

server:
  address: 0.0.0.0
  port: 8080