spring:
  application:
    name: Premier

  #  datasource:
  #    url: jdbc:sqlite:test1.3.db
  #    driver-class-name: org.sqlite.JDBC

  datasource:
    url: jdbc:postgresql://ep-lucky-darkness-a19d99aq-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
    username: neondb_owner
    password: npg_SpWJwg5T1Bbs

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

#  jpa:
#    database-platform: org.hibernate.community.dialect.SQLiteDialect
#    hibernate:
#      ddl-auto: update

  mail:
    host: smtp.gmail.com
    port: 587
    username: thanhvu7623@gmail.com
    password: brev bago trwi eeko
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

URL_frontend: http://127.0.0.1:5500

#logging:
#  level:
#    root: DEBUG  # Set the log level for the root logger
#    org.springframework: DEBUG  # Set the log level for Spring Framework
#    org.hibernate: DEBUG  # Set the log level for Hibernate
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.tool.hbm2ddl: DEBUG
    org.hibernate: DEBUG  # Set the log level for Hibernate

jwt:
  signerKey: KpDU0T82a7oaCgJ5Z98BlR2kIzDiliRHGgXL/xCo2LSjxeJ0tvkaDtWazIPxeP7m

server:
  address: 0.0.0.0
  port: 8080